import { useEffect,useMemo,useState } from 'react';
import { ArrowUpRight, ShieldCheck, Activity, Video, HeartPulse } from 'lucide-react';
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid } from 'recharts';
import { api } from '../services/api'; import { useAppStore } from '../store/appStore'; import { MetricCard } from '../components/MetricCard';
export function Dashboard({go}:{go:(p:string)=>void}){
 const athlete=useAppStore(s=>s.athlete); const mode=useAppStore(s=>s.network); const [items,setItems]=useState<any[]>([]);
 useEffect(()=>{api<any[]>(`/api/assessment?athlete_id=${athlete?.id||1}`,undefined,mode).then(setItems).catch(()=>setItems([]))},[athlete,mode]);
 const latest=items[0]; const chart=useMemo(()=>[...items].reverse().map((a,i)=>({name:`A${i+1}`,score:a.readiness_score,pain:a.pain})),[items]);
 return <div className="page-grid"><section className="hero-card"><div><div className="eyebrow">CURRENT READINESS INDICATOR</div><div className="score-row"><div className="score">{latest?.readiness_score??'—'}</div><span>/100</span></div><div className={`status-tag ${latest?.status?.toLowerCase()||'neutral'}`}>{latest?.status||'NO ASSESSMENT'}</div><p>{latest? 'Ready for Further RTP Evaluation is only shown when a trained model produced this result.':'Complete an assessment after installing a real trained model.'}</p></div><div className="hero-icon"><ShieldCheck size={48}/></div></section><div className="metric-grid"> <MetricCard label="Movement Quality" value={latest?.movement_quality??'—'}/><MetricCard label="Symmetry" value={latest?.symmetry??'—'}/><MetricCard label="ROM" value={latest?.rom??'—'}/><MetricCard label="Stability" value={latest?.stability??'—'}/><MetricCard label="Pain" value={latest?.pain??'—'} unit="/10"/><MetricCard label="Psychological Readiness" value={latest?.psychological_readiness??'—'}/></div><section className="card chart-card"><div className="card-head"><div><h2>Recovery Trend</h2><p>Readiness and pain across completed assessments.</p></div><button className="ghost" onClick={()=>go('trend')}>Open trend <ArrowUpRight size={16}/></button></div>{chart.length?<div className="chart"><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><CartesianGrid vertical={false} strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Line type="monotone" dataKey="score" stroke="#165DFF" strokeWidth={3} dot={{r:4}}/><Line type="monotone" dataKey="pain" stroke="#E5484D" strokeWidth={2}/></LineChart></ResponsiveContainer></div>:<div className="empty">No assessments yet.</div>}</section><section className="card quick-grid"><button onClick={()=>go('assessment')}><Video/><b>New Assessment</b><span>Camera or compressed video upload</span></button><button onClick={()=>go('assistant')}><HeartPulse/><b>Recovery Support</b><span>Explain current indicators</span></button><button onClick={()=>go('history')}><Activity/><b>History</b><span>Review previous assessments</span></button></section></div>
}
